### PR TITLE
More generic "extensions" parameter for Markdown

### PR DESCRIPTION
**Pull request by Zopieux**
In the current state, users can only provide a comma-separated list of extension paths in `MARKDOWN_EXTENSIONS`. This prevents the users from setting extension-specific parameters such as `TocExtension(marker="--TOC--", permalink=True)`

In this patch we only do the splitting if the extension parameter is a string (using `six.string_types` of course) so the caller can use a list of Extension instances instead. Docstring was updated accordingly.

### CODE REVIEW

**Comment by Zopieux** [comment]
I'll add a test case in `test/markups.py` as soon as I am back home. You may want to wait until they're appended to this PR before merging. :lollipop:

**Comment by Zopieux** [comment]
Test added, this should be merge-ready.

**Comment by Fantomas42** [comment]
Thanks @Zopieux for your work.

Your work has been merged at https://github.com/Fantomas42/django-blog-zinnia/commit/9b82fb4498ae95df1ad6a0e300de01963de04a2b

With your idea the markdown extension are really better.

**Comment by Zopieux** [comment]
Thanks!

**Pull request closed without merging**
