### PR TITLE
Added Opengraph meta tag to entries

### PR DESCRIPTION
**Pull request by ZuluPro**
Added tags 'meta' in entries' template for support Open Graph Protocol.
See http://ogp.me/ for more informations about it.

I added this to `zinnia/entry_detail_base.html` template only, maybe you want it in other pages ?

### CODE REVIEW

**Comment by ZuluPro** [comment]
Re-up

**Comment by ZuluPro** [comment]
I just rebased from master.

**Comment by ZuluPro** [comment]
@Fantomas42 Any news ?

**Comment by Fantomas42** [comment]
Hello @ZuluPro 

first of all, thank you for your pull-request !

But unfortunately, I cannot merge it for several reasons:

- Zinnia try to be agnostic on the implementations and OpenGraph is mostly used by Facebook, so this implementation is too specific to be included into the core.

- Theses modifications can easily be done on the templates, so this is the user's responsability to enable it if he want to.

- Severals Django applications are dedicated for doing this, so it should be a better idea to use one of these apps.

- The provided implementation is too light and specific, and only concern the detail page, which annoy me.

Best regards

**Pull request closed without merging**
